version: '3.8'
services:
  jupyter:
    image: jupyter/datascience-notebook:x86_64-python-3.11.6
    container_name: jupyter-lab
    ports:
      - "${JUPYTER_PORT}:8888"
    volumes:
      - ${WORK_DIR}:/home/jovyan/work
    env_file:
      - .env
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      NB_PASSWORD: ${JUPYTER_PASSWORD}
    command: start-notebook.sh --NotebookApp.token='' --NotebookApp.password='${NB_PASSWORD}'
