services:
  memgraph-platform:
    image: "memgraph/memgraph-platform:2.13.0"
    network_mode: host
    ports:
      - "7687:7687"
      - "3000:3000"
      - "7444:7444"

    volumes:
      - mg_lib:/var/lib/memgraph 
      - mg_log:/var/log/memgraph 
      - mg_etc:/etc/memgraph 
      - ./ind.cypherl:/usr/lib/memgraph/ind.cypherl 
      - modules:/usr/lib/memgraph/query_modules
    
    env_file:
      - .env

    entrypoint: ["/usr/bin/supervisord"]
    restart: always
    
volumes:
  mg_lib:
  mg_log:
  mg_etc:
  modules:
